package advent2022.day02;

import java.util.Arrays;
import java.util.List;

public class Datas {

	public final static List<String> entrees = Arrays.asList("CX", "CY", "CX", "BX", "BZ", "AZ", "CY", "CZ", "BZ", "CX",
			"BY", "CY", "CY", "AY", "CY", "CY", "CZ", "CX", "BZ", "CY", "AY", "AY", "CZ", "BY", "AY", "CZ", "CY", "AY",
			"AY", "BY", "CY", "CZ", "CY", "BX", "BZ", "CY", "BZ", "AX", "CZ", "AY", "BY", "CY", "CY", "BZ", "BY", "AZ",
			"CX", "CX", "CY", "CX", "BZ", "AY", "BX", "BZ", "CZ", "CX", "CX", "BZ", "AY", "BY", "CY", "CY", "AY", "CX",
			"AY", "BZ", "CY", "CY", "BY", "CY", "AZ", "AZ", "BX", "AY", "CY", "AY", "CY", "CY", "CX", "CY", "BZ", "CY",
			"CZ", "CX", "BX", "CY", "CY", "CX", "CZ", "AY", "CX", "BZ", "CX", "AY", "BY", "CY", "AY", "AY", "AY", "BY",
			"CY", "AY", "AY", "CZ", "CY", "BY", "CX", "CY", "BZ", "BZ", "CX", "CY", "CX", "CY", "CY", "AY", "CY", "CX",
			"CY", "CY", "BY", "BZ", "AY", "BY", "AY", "AY", "CY", "BX", "CY", "CX", "AY", "CX", "CX", "CY", "CY", "BZ",
			"CX", "AY", "BZ", "CZ", "CX", "AY", "BZ", "CY", "BY", "AY", "AY", "CY", "BY", "CY", "CX", "CY", "AY", "CY",
			"AY", "BY", "CX", "CY", "CY", "BZ", "BZ", "AY", "CY", "CY", "CY", "CY", "AY", "CX", "CZ", "CX", "AY", "AY",
			"AY", "CY", "BZ", "BZ", "CY", "CY", "BX", "CY", "CY", "BZ", "BX", "BY", "CY", "CY", "CX", "BY", "BZ", "BZ",
			"CY", "CY", "CX", "CX", "AY", "CY", "CY", "BX", "BZ", "BX", "BZ", "BY", "CX", "BX", "BY", "BZ", "BZ", "BX",
			"BZ", "BY", "CX", "CY", "CX", "CX", "BZ", "CY", "CY", "CY", "BZ", "CY", "CX", "CY", "CY", "AZ", "CY", "AY",
			"CY", "AZ", "AX", "CY", "CY", "CY", "CZ", "BZ", "BZ", "CY", "BZ", "BZ", "CX", "CY", "AY", "AY", "CY", "AY",
			"CY", "CY", "BY", "AY", "CY", "BZ", "AY", "BZ", "CX", "CY", "AY", "BZ", "AY", "CX", "CY", "BY", "CY", "AZ",
			"BZ", "BX", "CY", "AY", "AZ", "CX", "AY", "BZ", "AY", "BY", "CY", "CY", "BZ", "BZ", "CX", "BZ", "CX", "CZ",
			"CY", "CX", "AY", "CX", "AY", "AY", "BZ", "BZ", "BZ", "AY", "AY", "CY", "AY", "BZ", "CX", "CY", "CY", "CY",
			"BY", "AY", "CZ", "CY", "AY", "AY", "BZ", "CY", "CY", "CY", "BZ", "CY", "CY", "AY", "AY", "CY", "CX", "BZ",
			"BZ", "CX", "CX", "CZ", "AY", "CY", "AY", "AY", "CX", "AZ", "BY", "AY", "CX", "AY", "CX", "CX", "AY", "AY",
			"CX", "BY", "BZ", "CY", "CZ", "CY", "CY", "BZ", "CY", "AY", "AX", "BY", "CY", "AY", "CY", "CY", "CY", "AY",
			"CY", "AY", "CY", "BZ", "AY", "CX", "CY", "AY", "CY", "AY", "AY", "AY", "BZ", "CY", "BZ", "AY", "CY", "AY",
			"CY", "CX", "BZ", "AY", "CX", "BZ", "BY", "CY", "CZ", "CY", "BY", "BY", "AY", "AY", "CX", "BY", "AY", "CY",
			"BX", "CX", "AY", "CY", "AY", "CY", "BZ", "AZ", "BZ", "BZ", "AZ", "CY", "CY", "CX", "BY", "CY", "AY", "CY",
			"CY", "BY", "BZ", "CY", "CX", "AY", "CX", "CX", "CY", "BY", "CY", "BZ", "CY", "AY", "AY", "CY", "CX", "CX",
			"CX", "CY", "CX", "CY", "CY", "AY", "CY", "CX", "CY", "CX", "CX", "CX", "AY", "BY", "CY", "CY", "CY", "CY",
			"CY", "AY", "AX", "BZ", "CX", "CY", "CY", "BZ", "AY", "AY", "BX", "BZ", "CY", "CY", "BZ", "AY", "AY", "AY",
			"CY", "CY", "AY", "AY", "CY", "CY", "CX", "CX", "CX", "BZ", "CZ", "CX", "AZ", "CY", "CX", "AY", "BY", "BZ",
			"CX", "CY", "CY", "CZ", "CY", "CX", "AZ", "CY", "AX", "BY", "CY", "CY", "CY", "CX", "BY", "BY", "CX", "BX",
			"AY", "CY", "CY", "CY", "BX", "CY", "AY", "CY", "CY", "BZ", "CX", "BX", "CZ", "CY", "AY", "BY", "BZ", "CZ",
			"CX", "CX", "AY", "AY", "BZ", "AY", "CX", "BY", "CY", "AY", "BX", "AY", "AY", "CZ", "CY", "CZ", "BZ", "AX",
			"CY", "BY", "CY", "BZ", "BY", "CY", "AY", "BZ", "BZ", "CX", "BZ", "CY", "BZ", "BZ", "CY", "CY", "BZ", "CZ",
			"CY", "BZ", "CY", "BX", "AY", "BZ", "AY", "CY", "AY", "CY", "CY", "BY", "BZ", "BZ", "CY", "AY", "BZ", "CX",
			"CY", "CY", "AY", "CY", "CY", "CX", "AY", "CY", "CY", "AY", "CX", "AY", "AY", "AY", "CY", "CY", "AY", "BZ",
			"AY", "BY", "AY", "AY", "CY", "CY", "CZ", "AY", "CY", "BZ", "AY", "CY", "CZ", "CY", "CY", "BZ", "CY", "CY",
			"BZ", "BY", "CY", "AY", "CX", "CY", "CZ", "CZ", "CX", "CX", "CX", "CZ", "CY", "BZ", "AY", "BZ", "BZ", "AY",
			"CY", "CY", "CY", "BX", "CY", "AY", "AZ", "BY", "BY", "AY", "BZ", "AY", "BY", "CZ", "CY", "CY", "CY", "BZ",
			"BZ", "BZ", "CY", "CY", "AY", "CX", "CX", "AY", "CY", "CY", "CY", "CY", "CX", "CY", "CY", "CY", "CX", "AZ",
			"BY", "CY", "AY", "AY", "BZ", "AZ", "CY", "CY", "CY", "CX", "BX", "BY", "CY", "AY", "AZ", "BX", "CY", "CY",
			"BZ", "AY", "AY", "BZ", "BZ", "CY", "CY", "CX", "BY", "BZ", "CY", "BY", "CY", "AY", "CX", "CX", "BZ", "AY",
			"CY", "BZ", "CX", "CY", "BY", "BZ", "AZ", "BY", "BY", "CX", "CY", "AZ", "CX", "CX", "AY", "AY", "CX", "AY",
			"BY", "BZ", "AY", "BZ", "BX", "CY", "CY", "CX", "BZ", "AY", "BY", "AY", "CY", "CZ", "BZ", "CY", "AY", "CY",
			"CZ", "AZ", "BZ", "BX", "CY", "CY", "BY", "CX", "BY", "BZ", "BZ", "BX", "BY", "CX", "CY", "CX", "CY", "AY",
			"AY", "CY", "AY", "CY", "CX", "CY", "AY", "BZ", "CX", "CY", "BZ", "CY", "CY", "BY", "BZ", "AX", "CY", "BY",
			"BY", "BZ", "CY", "BZ", "AY", "CY", "BY", "CY", "AY", "CY", "BZ", "CY", "AY", "AY", "CY", "AY", "CY", "AY",
			"AY", "BZ", "CX", "CY", "BZ", "CY", "AX", "AZ", "CY", "CX", "CX", "CY", "CY", "BZ", "AZ", "AY", "CY", "BZ",
			"AY", "AY", "CY", "BZ", "AY", "CX", "AY", "AY", "CX", "BZ", "BX", "AX", "AY", "BY", "AX", "BX", "CX", "CY",
			"AY", "CY", "AY", "AY", "CX", "BY", "CX", "BY", "CY", "CY", "AY", "BZ", "AZ", "BY", "CX", "CY", "CY", "BZ",
			"CZ", "AY", "AY", "AZ", "CY", "AY", "BZ", "CY", "CY", "BY", "AY", "AY", "CY", "CX", "CX", "BY", "BZ", "CY",
			"BY", "BZ", "CY", "AY", "BZ", "AY", "AY", "AZ", "CX", "BZ", "CY", "BZ", "AY", "CX", "CY", "CY", "BX", "BZ",
			"AY", "AY", "AY", "AY", "AY", "CY", "AY", "AY", "CX", "CY", "CZ", "BZ", "AZ", "CZ", "AY", "BZ", "BY", "AY",
			"CY", "BZ", "AY", "CY", "CY", "AY", "CY", "BZ", "BY", "BZ", "CY", "CY", "CY", "AZ", "CX", "BX", "BZ", "CZ",
			"CY", "CY", "CY", "CX", "AY", "CY", "AY", "AY", "BZ", "AY", "CY", "CY", "AY", "CY", "AZ", "BX", "AY", "CY",
			"AY", "AZ", "AY", "AY", "BZ", "BY", "BZ", "CY", "BZ", "CX", "AY", "CY", "AY", "AY", "AY", "BZ", "BZ", "CY",
			"BZ", "BY", "CX", "AY", "CY", "AY", "BZ", "CX", "BY", "CY", "BZ", "CY", "AY", "CY", "CY", "BY", "BZ", "CY",
			"BZ", "BY", "CY", "CX", "AZ", "CZ", "CY", "CY", "AY", "AY", "CX", "CY", "CY", "CY", "CX", "BZ", "CX", "CY",
			"AY", "AY", "BZ", "AY", "AY", "CY", "AY", "BZ", "CX", "CY", "CY", "CY", "CY", "CX", "BZ", "AY", "BY", "CY",
			"CX", "BZ", "CY", "AY", "AY", "BZ", "CY", "AY", "CZ", "CX", "BZ", "CY", "AZ", "BZ", "AY", "AY", "CY", "BZ",
			"BZ", "AY", "CY", "BY", "CY", "AY", "AY", "BY", "BX", "BZ", "CY", "AY", "CY", "AY", "AY", "BZ", "BY", "AY",
			"AY", "AY", "CY", "BY", "CY", "AY", "CX", "CY", "CY", "BZ", "BZ", "CY", "CY", "AY", "BX", "CX", "AY", "CY",
			"CY", "CY", "AY", "CX", "BZ", "AY", "CZ", "BY", "BY", "CZ", "AY", "CZ", "CY", "CX", "BY", "AY", "CX", "CX",
			"CY", "CX", "CX", "BZ", "CY", "BY", "AY", "BY", "AY", "BZ", "CX", "CY", "CX", "CZ", "CX", "BZ", "CX", "CY",
			"CY", "CY", "BZ", "AY", "CY", "CY", "CY", "BZ", "AY", "CX", "CY", "CY", "CY", "CX", "AZ", "CY", "CY", "CX",
			"BX", "BZ", "AY", "BZ", "CY", "BY", "BZ", "AY", "BZ", "CY", "AY", "AX", "CX", "CX", "CY", "AY", "BX", "CY",
			"BX", "BZ", "CX", "AY", "BX", "CX", "AY", "CY", "CY", "CY", "AZ", "CY", "AY", "BZ", "BZ", "AZ", "CY", "AY",
			"BZ", "CZ", "CX", "CX", "CX", "AY", "AX", "CY", "AY", "BY", "CY", "CX", "CY", "CY", "AY", "BZ", "CY", "BZ",
			"AY", "CX", "CY", "BZ", "CY", "CY", "BY", "AY", "AY", "AZ", "CY", "BZ", "BY", "BZ", "BY", "AY", "CY", "CY",
			"CX", "CY", "CY", "BZ", "CY", "CY", "CX", "BY", "BZ", "CY", "CY", "AY", "CZ", "CY", "BZ", "AY", "AX", "AY",
			"CX", "CY", "CY", "BZ", "AY", "BX", "CZ", "CZ", "CX", "CY", "BZ", "CZ", "BZ", "CY", "AY", "CY", "AY", "BX",
			"CX", "CY", "BZ", "CY", "BY", "BX", "BX", "BZ", "CY", "CY", "BY", "BZ", "CY", "AY", "BZ", "CY", "BZ", "CY",
			"BZ", "CY", "AY", "AY", "CY", "CY", "BY", "BZ", "CY", "BZ", "CX", "BZ", "CY", "BX", "CX", "BZ", "AY", "CX",
			"BZ", "CY", "AY", "BZ", "AX", "BZ", "BZ", "BZ", "CY", "CY", "CY", "CY", "AY", "AY", "BZ", "BX", "CX", "CY",
			"BY", "AY", "AY", "BZ", "CY", "AY", "AY", "CY", "CX", "CY", "CX", "CY", "CY", "CY", "BZ", "CY", "CX", "BY",
			"CY", "CY", "CY", "AZ", "CX", "CY", "AY", "CY", "BZ", "BY", "CY", "AY", "AY", "CY", "CY", "CX", "AY", "CY",
			"AZ", "AY", "BZ", "AY", "CX", "CY", "CY", "BX", "BZ", "CX", "BX", "CZ", "CX", "BZ", "BZ", "CY", "CX", "BZ",
			"BZ", "BZ", "CY", "CY", "AY", "CY", "BY", "BX", "CY", "CY", "CY", "BX", "CX", "BX", "CY", "AY", "CY", "CX",
			"CY", "CY", "BX", "BZ", "AZ", "BZ", "AY", "BZ", "CX", "BZ", "CY", "CY", "CZ", "AY", "CY", "CY", "AZ", "BY",
			"CY", "AX", "AY", "BY", "CY", "BZ", "CY", "CX", "CY", "BZ", "AY", "CX", "CY", "CX", "CY", "CY", "CZ", "AY",
			"CY", "BZ", "AY", "CZ", "CY", "AY", "CY", "CY", "CY", "CY", "AY", "CY", "CY", "CY", "CY", "BZ", "CX", "AY",
			"AY", "CY", "BY", "CY", "CY", "AZ", "CY", "BY", "CY", "BZ", "CX", "AY", "CY", "CY", "BZ", "CY", "AY", "AY",
			"CY", "BZ", "CY", "AY", "BZ", "CY", "CY", "BZ", "CX", "BZ", "BZ", "CY", "CY", "AY", "CX", "AY", "CY", "BZ",
			"AY", "BZ", "AY", "CX", "CY", "BZ", "BY", "BZ", "AY", "BZ", "CY", "BZ", "CY", "BY", "AY", "BZ", "BX", "BZ",
			"CY", "BZ", "BZ", "BZ", "AY", "AY", "CY", "BZ", "BZ", "CX", "BZ", "CZ", "AY", "BZ", "BZ", "CY", "BZ", "BZ",
			"CX", "CZ", "AZ", "CY", "CY", "BX", "CZ", "CY", "AY", "BZ", "CX", "BZ", "CY", "CY", "BZ", "BZ", "BZ", "CX",
			"CY", "CX", "CX", "AY", "BZ", "BY", "CY", "CY", "BZ", "CY", "CY", "CY", "CY", "CY", "BX", "AY", "AY", "BY",
			"CY", "BY", "CY", "BY", "BZ", "CY", "CY", "CX", "BY", "AY", "BX", "BZ", "CX", "AX", "CY", "AY", "AY", "CX",
			"BY", "AY", "BZ", "CX", "BZ", "CZ", "CX", "CY", "CX", "CY", "CY", "CY", "BY", "CZ", "CX", "BZ", "CY", "CX",
			"CX", "BY", "CY", "CY", "CZ", "BZ", "CY", "CY", "BY", "CZ", "CX", "BZ", "CY", "CX", "CY", "BZ", "CY", "CY",
			"AY", "BY", "CX", "CY", "CY", "CY", "BY", "BY", "CZ", "BZ", "CY", "BZ", "AZ", "CX", "BX", "CX", "AY", "CY",
			"AZ", "CX", "CY", "AY", "AY", "BY", "AY", "CY", "BY", "CX", "CX", "CX", "CX", "CY", "CY", "AY", "BZ", "CY",
			"AZ", "CY", "AY", "BZ", "BZ", "CY", "AZ", "CY", "CY", "CY", "BZ", "CY", "CY", "AX", "AY", "AZ", "CY", "AY",
			"BX", "AY", "BZ", "BY", "BZ", "BY", "CX", "CX", "AY", "BZ", "BY", "CX", "BX", "BY", "AY", "CY", "CY", "CY",
			"BZ", "CY", "AY", "BZ", "CX", "BZ", "BZ", "BX", "BY", "CY", "CY", "CX", "BZ", "CY", "CY", "CY", "AY", "CY",
			"BZ", "BY", "CY", "CX", "CX", "BX", "BZ", "AZ", "CX", "AY", "BY", "CY", "AY", "BY", "CY", "CY", "CZ", "CY",
			"CX", "AY", "CY", "CY", "BZ", "CY", "CY", "CY", "CY", "AY", "BZ", "BZ", "CY", "CY", "CY", "CY", "CY", "BZ",
			"CY", "CY", "CX", "AY", "AY", "CY", "CX", "AY", "BZ", "AY", "CX", "CY", "CZ", "CY", "AZ", "AY", "AY", "BY",
			"CY", "CY", "BY", "CY", "AY", "CX", "BZ", "CX", "AY", "BZ", "CX", "AY", "CX", "CX", "AZ", "AY", "BY", "AY",
			"BY", "AZ", "CY", "CY", "CY", "BZ", "CY", "AY", "BZ", "BY", "CY", "BY", "CZ", "AY", "BY", "CY", "BY", "AY",
			"BZ", "CY", "CX", "CY", "AY", "AZ", "CY", "BZ", "CY", "BY", "AY", "CX", "AZ", "CZ", "CX", "AY", "CX", "CX",
			"CY", "CZ", "AY", "AY", "CY", "AY", "CY", "BZ", "CX", "AX", "CX", "CY", "CY", "CY", "CY", "BZ", "BZ", "BZ",
			"CX", "CY", "BY", "CY", "BY", "CZ", "AX", "BY", "CX", "BY", "CX", "BY", "CY", "BZ", "CX", "AY", "BZ", "CX",
			"AX", "CY", "BZ", "BZ", "CX", "BZ", "BZ", "CX", "CY", "CZ", "BZ", "CY", "CY", "CY", "BX", "AY", "BY", "BZ",
			"BZ", "CX", "AZ", "CY", "CY", "AY", "AX", "AY", "CY", "BY", "CY", "AY", "CX", "CY", "CY", "CY", "CY", "CY",
			"CY", "CY", "CY", "CY", "CY", "BZ", "BZ", "AY", "BY", "CY", "CY", "CX", "BZ", "AY", "CY", "BZ", "CY", "AY",
			"CX", "BX", "CZ", "AY", "CX", "BY", "CX", "BZ", "AY", "CY", "CY", "CY", "BZ", "BZ", "AZ", "CZ", "AY", "BZ",
			"CX", "CY", "AY", "CY", "CY", "CX", "BZ", "CZ", "CY", "BZ", "AX", "BY", "AZ", "BX", "CX", "AY", "CY", "BZ",
			"BZ", "CY", "AY", "BZ", "BZ", "AY", "AY", "BZ", "BZ", "AX", "BZ", "CY", "CZ", "CY", "CY", "BZ", "CY", "AZ",
			"AX", "CX", "BY", "BZ", "CX", "BZ", "AX", "AY", "AY", "BX", "BY", "BZ", "CX", "CX", "CX", "CY", "CY", "BX",
			"CY", "CY", "AY", "CX", "AY", "BZ", "AY", "CY", "BX", "CX", "CY", "AY", "CX", "CY", "CY", "BZ", "AY", "AY",
			"AZ", "CY", "BZ", "AZ", "BX", "AZ", "CY", "BX", "AY", "CY", "CZ", "AZ", "CX", "AY", "BX", "CY", "CY", "CX",
			"CZ", "AY", "AY", "CY", "BZ", "CY", "CX", "BX", "AY", "BY", "BZ", "BZ", "CY", "CY", "AY", "BZ", "BZ", "CY",
			"CZ", "CY", "CY", "CX", "CX", "AY", "BZ", "AY", "BZ", "BZ", "CX", "BX", "CX", "CY", "BX", "BZ", "CX", "CX",
			"CX", "BZ", "BY", "BZ", "CY", "CY", "BZ", "BY", "BZ", "CY", "BY", "AY", "AY", "BY", "AY", "BZ", "AY", "CX",
			"AY", "CZ", "BY", "CY", "CX", "CX", "CY", "CX", "CY", "AY", "BZ", "CX", "CY", "CY", "CY", "CY", "CY", "BY",
			"AY", "BZ", "CY", "AZ", "CY", "BZ", "CX", "CZ", "AY", "BZ", "CX", "CY", "BZ", "CY", "AY", "CY", "CX", "CX",
			"CY", "AY", "BY", "AX", "CY", "CY", "AY", "CY", "AX", "CY", "BY", "CX", "BZ", "BZ", "BY", "CY", "CZ", "CX",
			"BZ", "BZ", "BY", "CZ", "AY", "CY", "CY", "BY", "CX", "AY", "CY", "CY", "AZ", "AY", "BY", "CY", "CY", "CX",
			"BX", "CY", "AY", "BZ", "BY", "AY", "BY", "CY", "CX", "CY", "CY", "CX", "AY", "BZ", "CX", "CZ", "BX", "CY",
			"CX", "CY", "CX", "CY", "BZ", "AY", "AY", "BZ", "CY", "CY", "BZ", "CY", "CX", "BZ", "CY", "BZ", "CX", "CY",
			"CX", "AY", "CY", "AX", "CY", "CX", "AY", "CY", "AY", "CY", "AY", "CX", "AY", "AY", "AY", "BY", "BZ", "CY",
			"BZ", "AY", "CY", "CX", "BX", "CY", "BZ", "BX", "BX", "BY", "CY", "CX", "CY", "CX", "BY", "BZ", "AY", "BY",
			"CY", "CZ", "AY", "CY", "BY", "AY", "CX", "CY", "AY", "CY", "AZ", "CZ", "CY", "BZ", "CY", "CY", "BY", "AY",
			"CZ", "AX", "CY", "BZ", "CZ", "BX", "CY", "CX", "CX", "BZ", "BZ", "BX", "BY", "CY", "BZ", "BZ", "BZ", "AY",
			"BZ", "CY", "CY", "AY", "AX", "CZ", "AY", "CZ", "CY", "CX", "CY", "CX", "BZ", "CY", "AX", "BZ", "BY", "CY",
			"BY", "CY", "CY", "AY", "BZ", "BY", "CY", "CX", "CY", "CY", "BZ", "AY", "BX", "CY", "CY", "CY", "AY", "CY",
			"CY", "CX", "CZ", "CX", "BY", "AY", "CZ", "BZ", "BZ", "AY", "CY", "CX", "BX", "CX", "BZ", "AY", "CY", "CY",
			"BZ", "AY", "BY", "CX", "BY", "BZ", "BZ", "BZ", "BX", "BY", "BZ", "CX", "AZ", "AY", "CY", "AY", "CY", "CY",
			"BZ", "BZ", "CX", "BX", "CY", "AZ", "CY", "CX", "CY", "BY", "CX", "BZ", "CY", "CX", "BZ", "AY", "AY", "CY",
			"AY", "AZ", "CY", "AZ", "AY", "CY", "CX", "BX", "CY", "CY", "CX", "AY", "CX", "CY", "BZ", "BX", "CY", "AY",
			"BX", "CY", "BY", "CX", "AY", "BZ", "CY", "CY", "BZ", "AY", "AZ", "CY", "CY", "CX", "AY", "BZ", "BZ", "BY",
			"BZ", "AY", "CY", "AY", "BY", "AY", "CX", "CY", "AZ", "AZ", "BY", "AY", "CY", "AX", "CY", "CY", "BZ", "CY",
			"CX", "CY", "AY", "CY", "CY", "CY", "CY", "AX", "CY", "BY", "CY", "AY", "CY", "CX", "CX", "CZ", "BZ", "AY",
			"BX", "CY", "CY", "CY", "AY", "BZ", "BZ", "CY", "AY", "BZ", "AY", "CX", "CX", "AY", "CZ", "CY", "BZ", "BZ",
			"AY", "AY", "CY", "AY", "CY", "AY", "BZ", "CX", "CY", "CY", "AY", "CY", "AY", "AZ", "BY", "CY", "CX", "AY",
			"CX", "AX", "CY", "CY", "BY", "CY", "BZ", "AY", "CX", "BZ", "AY", "CX", "BZ", "AY", "CY", "BZ", "AY", "BZ",
			"CX", "CY", "CX", "CY", "BZ", "CY", "BY", "CZ", "BZ", "CY", "CY", "AX", "CX", "AY", "CY", "BZ", "AY", "AZ",
			"BZ", "CY", "CY", "AY", "AY", "AY", "CX", "CY", "AZ", "CY", "CZ", "AY", "AY", "CY", "CX", "CX", "CZ", "CY",
			"CZ", "BZ", "AY", "BZ", "BZ", "CX", "AY", "BY", "AY", "AZ", "AY", "CY", "CY", "CZ", "AY", "CY", "BY", "CX",
			"CX", "BX", "CY", "AY", "CZ", "AY", "BZ", "BY", "CY", "AY", "AY", "CY", "CY", "CY", "CY", "CY", "CY", "CY",
			"AY", "BY", "AY", "BY", "BY", "CX", "CX", "CY", "AY", "CY", "CY", "CZ", "CY", "CY", "BY", "CY", "BY", "AY",
			"CY", "BZ", "CX", "CY", "AZ", "AZ");

	public static List<String> getEntrees() {
		return entrees;
	}

}
